# Generated by Django 4.1.5 on 2023-01-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_phone_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
