# Generated by Django 4.1.5 on 2023-01-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_follower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='UserFollower',
        ),
    ]
