# Generated by Django 4.1.5 on 2023-01-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userfollower_from_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollower',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
